name: Bulk Replace & Update

on:
  workflow_dispatch:  # This lets you run it manually

jobs:
  update-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow writing changes back
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Replace phone number in all HTML files
        run: |
          find . -name "*.html" -exec sed -i 's/512.475.1300/dob.texas.gov@hotmail.com/g' {} \;
      
      - name: Commit and push changes
        run: |
          git config --global user.name "dob-texas-gov"
          git config --global user.email "tifma.dob.texas.gov@gmail.com"
          git add .
          git commit -m "Bulk update: Replace phone number with email"
          git push
